### PR TITLE
Added updated NIRCam tutorial

### PR DESCRIPTION
**Pull request by kglidic**
The following are the reduction and contrast analysis notebooks for NIRCam using spaceKLIP. These notebooks provide additional details and descriptions of the concepts and results, tailored for new users of both spaceKLIP and high-contrast imaging. This PR also introduces more plotting capabilities, including a comparison plot for intermediate results and improvements in how plots and tables are printed in the notebook and saved.

### CODE REVIEW

**Comment by AarynnCarter** [comment]
Hi Kayli, 

Awesome work, this is almost there! Having issues with PyCharm so have to put my comments here:

- [ ] I think the webbpsf_ext style issue might be fixed in the latest version
- [ ] I think we should change mentions of "Level N" reductions to "Stage N" reductions, as they better line up with the nomenclature that the pipeline uses. 
- [ ] When running KLIP, just use 1 annulus to cut down on the number of figures later on
- [ ] None of the interactive plots are displaying for me after cloning the branch... Maybe I need some dependency?  This is the error I get: `IntSlider(value=0, description='Image  Index:', max=5) Output()`
- [ ] Residual ** comment in Raw Contrast description
- [ ] Discuss aspects of contrast curves a little more explicitly. Specifically, explain how the raw contrast curve is affected by the coronagraphic throughput / what causes the differencs, then for the calibrated contrast, describe how the KLIP throughput varies (i.e. more oversubtraction close to the star, but less further out).
- [ ] Finish the analysis tutorial with a comparison to my ERS paper on HIP 65426b. Specifically, the appmag measured there was 15.467±0.078, and this is consistent to 1 sigma to the tutorial values (and doesn't perform the same error analysis as done in the ERS paper). Differences are due to various updates to both the JWST pipeline and spaceKLIP.

**Comment by AarynnCarter** [comment]
Ah and another one:

- [ ] I think you need to add ipywidgets to the requirements so that the CI tests will work.

**Comment by mperrin** [comment]
The interactive plot display works, but I get a bunch of extra warning text from every `display_coron_dataset` call, and also for `display_image_comparisons`. This outputs over and over again for every time one of the sliders is clicked to adjust the displayed image number, which is super annoying.   I don't understand what has turned on these `py.warnings:WARNING` messages, which I don't recall having seen before. Sigh. 
```
[py.warnings:WARNING] /Users/mperrin/Dropbox (Personal)/Documents/software/git/spaceKLIP/spaceKLIP/plotting.py:280: RuntimeWarning: Mean of empty slice
[py.warnings:WARNING]   image = np.nanmean(model.data, axis=0) if cube_ints else model.data
[py.warnings:WARNING] 
[py.warnings:WARNING] /Users/mperrin/miniconda3/envs/stenv-py3.11-2024.02.05/lib/python3.11/site-packages/astropy/wcs/wcs.py:807: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2022-07-30T05:06:00.117' from MJD-BEG.
[py.warnings:WARNING] Set DATE-AVG to '2022-07-30T05:11:09.069' from MJD-AVG.
[py.warnings:WARNING] Set DATE-END to '2022-07-30T05:16:18.022' from MJD-END'.
[py.warnings:WARNING]   warnings.warn(
[py.warnings:WARNING] 
[py.warnings:WARNING] /Users/mperrin/miniconda3/envs/stenv-py3.11-2024.02.05/lib/python3.11/site-packages/astropy/wcs/wcs.py:807: FITSFixedWarning: 'obsfix' made the change 'Set OBSGEO-L to   -67.360184 from OBSGEO-[XYZ].
[py.warnings:WARNING] Set OBSGEO-B to   -35.180767 from OBSGEO-[XYZ].
[py.warnings:WARNING] Set OBSGEO-H to 1706122045.054 from OBSGEO-[XYZ]'.
[py.warnings:WARNING]   warnings.warn(
[py.warnings:WARNING] 
[py.warnings:WARNING] /Users/mperrin/miniconda3/envs/stenv-py3.11-2024.02.05/lib/python3.11/site-packages/astropy/stats/sigma_clipping.py:438: AstropyUserWarning: Input data contains invalid values (NaNs or infs), which were automatically clipped.
[py.warnings:WARNING]   warnings.warn(
[py.warnings:WARNING] 
[py.warnings:WARNING] /Users/mperrin/Dropbox (Personal)/Documents/software/git/spaceKLIP/spaceKLIP/plotting.py:379: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
[py.warnings:WARNING]   fig.tight_layout(rect=[0.3, 0, 1, 1])
[py.warnings:WARNING] 
[py.warnings:WARNING] /Users/mperrin/Dropbox (Personal)/Documents/software/git/spaceKLIP/spaceKLIP/plotting.py:380: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
[py.warnings:WARNING]   fig.show()
[py.warnings:WARNING] 
```


Some relatively minor comments on the notebook text. 

- [ ] "two separate roll angles(`ROLL_REF`)"  I don't think the term ROLL_REF is used anywhere else, so I don't think that parenthetical is needed. 
- [ ] "custom spaceKLIP steps and parameters bolded—hover and click on the links for more details" This confused me a little, because I thought it meant that I could click on links to get details on those custom steps. But in fact it seems the links are actually just the step names linked to the steps in the regular pipeline docs? I suggest rephrasing slightly to clarify. 
- [ ] "The restrict_to parameter can, either". Minor: there's an extra comma there. 
- [ ] The paragraph starting "This is where we will do some extra image processing" is under the subsection header "Optional: Re-read Level 2 Outputs into Database", but that paragraph isn't part of the optional re-reading in inputs. I think another subsection header they're right above that would help clarify the organization. Perhaps "Using spaceklip ImageTools"
- [ ] "inormation" typo.

**Review by mperrin — APPROVED** [review]
Looks good!

**Pull request merged**
