### PR TITLE
Minor edits by Ell

### PR DESCRIPTION
**Pull request by ell-bogat**
* Enabled stellar spectrum generation using the Phoenix catalogs (for M dwarfs) via a keyword argument to WebbPSF
* Fixed a minor plotting error caused by having more than 13 images in the database
* Enabled frame-dependent bad pixel masks (i.e. you can make a 3D bad pixel mask)

### CODE REVIEW

**Comment by kammerje** [comment]
Hi @ell-bogat, thanks a lot for creating this PR! I'm happy to merge this, but there is one thing that might need further attention. In the meantime, I have fixed the missing outer working angle directly in the pyKLIP class (see https://github.com/kammerje/spaceKLIP/blob/dev/jk/spaceKLIP/pyklippipeline.py#L257) which I think is the more elegant solution. It is currently only part of the dev/jk branch, but will hopefully be merged into the develop branch properly soon.

**Comment by ell-bogat** [comment]
Gotcha, I can just revert the last commit so only the bp map and stellar spectrum catalog changes are included!

**Review by kammerje — APPROVED** [review]
Thanks @ell-bogat, this looks great!

**Comment by juliengirard** [comment]
awesome @ell-bogat I ran into that plotting error with too many images

**Pull request merged**
