### PR TITLE
Updating requirements.txt

### LINKED ISSUE #165: Define minimum versions in requirements.txt
The requirements files currently lists package dependencies, but not their minimum versions. We should take a look at these, perhaps on a recent install of spaceKLIP, and define minimum requirements to ensure that people are working across similar (and preferably identical) package versions.

### LINKED ISSUE #168: revisit stsci.stimage version dependency after it gets updated
See PR #167 and discussion there. We expect the pinned version dependency should be updated, once there's a new release of stimage which fixes that upstream issue.

### PR DESCRIPTION
**Pull request by AarynnCarter**
Pull request to resolve a few issues relating to our requirements file:

- [x] Update stimage to latest version, check for issues with CI
- [x] Define minimum version for packages based on personal current install

Resolves #168 and Resolves #165

### CODE REVIEW

**Comment by mperrin** [comment]
@AarynnCarter is this ready for review? I see you tagged me to review, but it's also still marked as a "Draft" PR only. I'll be happy to review but want to check it's ready first.

**Comment by AarynnCarter** [comment]
@mperrin Whoops, yes ready for a check.

**Review by mperrin — APPROVED** [review]
Looks good to me. One super tiny clarification query.

**Comment by AarynnCarter** [comment]
Nice catch @mperrin! Just fixed that and will merge.

**Pull request merged**
