### PR TITLE
Update + improve packaging setup

### PR DESCRIPTION
**Pull request by mperrin**
- Update installation configuration to use `pyproject.toml` which is the current/latest recommended standard (in the confusing maze of python packaging configuration options)
- Include data resources files as part of what gets installed when you do setup.py install. 
- Add supporting files for software license
- Update version configuration to use `setuptools_scm` to infer version information from git tags. (Currently this is defaulting to 0.1 since there are no version tags in this git repo)

Work in progress - there's likely some more stuff to ought to do as part of this.

### CODE REVIEW

**Comment by mperrin** [comment]
@kammerje @JarronL @wbalmer tagging you for situational awareness on this package setup refactoring

**Comment by AarynnCarter** [comment]
Hey @mperrin, I updated the resources paths, but I can't actually get the install working correctly. Whenever i attempt `import spaceKLIP` i get a `ModuleNotFoundError`. Did you manage to get it working on your end without the `sys.path.append('..')`?

**Comment by mperrin** [comment]
Yes the import is working for me. How are you installing it? Did you `python setup.py install` or something else?

**Comment by mperrin** [comment]
FYI, `_version.py` should not be added into git. See the comments in that file in which it explicitly states so: 
```
# file generated by setuptools_scm
 # don't change, don't track in version control
```

The way this works is, anytime you check out from git, or build a package for later installation, or install from GitHub, it will automatically look at the version tags in the repository, and figure out the version number from that, and _write that correct value_ to the `_version.py` file automatically

**Comment by mperrin** [comment]
Locally on my laptop, using this branch, I confirm I can `pip install .` to install `spaceKLIP` into the site-packages directory, and then run a copy of the the tutorial notebook _without_ needing to add anything to sys.path manually.  The tutorial runs all the way to the contrast step (same as for in the `tutorial` branch)

Given that, I assert this is working sufficiently well to be ready to merge. But I will defer to @AarynnCarter to give the approval.

**Pull request merged**
