### PR TITLE
Tutorial notebooks and some code improvements for version 2

### PR DESCRIPTION
**Pull request by mperrin**
- Update documentation text for `intro.rst`, using text drafted by @kammerje 
- Begin implementation of tutorial notebooks for V2, including reductions and post-pipeline analyses for each of NIRCam and MIRI
  - Current status is the tutorial notebooks for pipeline reduction work for both NIRCam and MIRI. 
  - The tutorials for post-pipeline analyses (measurements of contrast, photometry of the companion) do NOT work yet. 

- [ ] get example code working for the post-pipeline analyses steps. Now partially working for NIRCam. 
- [ ] Integrate examples from @AarynnCarter's plot_subimages and plot_contrasts scripts, and update to version 2 as needed (This depends on #86 first)
- [ ] Integrate these tutorials into the rest of the docs and provide links between pages as relevant. 

Now also includes the contents formerly in draft PR #81 to improve database and plotting tools for compatibility with level 3 outputs.

- enhance database.summarize function to also look at database.red as well as database.obs, and print a summary of the reduced files.
- enhance display_coron_dataset to know about stage3 files from database.red, and also display those. (Requires some extra steps in the plotting function since the pyklip outputs are organized differently than jwst pipeline outputs, so have to be read in differently.)

### CODE REVIEW

**Comment by mperrin** [comment]
This branch now also includes various small fixes and enhancements in the code, based on test runs of the tutorial notebooks.  See #87

**Comment by mperrin** [comment]
👍 Order of operations for which PR(s) to do first was exactly the sort of direction I was hoping you could clarify to me. Got it. Can prioritize #91 ahead of this one, will do. 

And yes, I would be strongly in favor of having a `dev` branch. My standard approach for `poppy`, `webbpsf`  and many other packages has been to have branches `develop` and `stable`, to clearly separate in-development merged PRs from stable "ready for general use" code.   So the pattern becomes many individual PRs -> get merged into `develop` over time -> eventually get ready for a release  -> merge `develop` to `stable` (or `main` equivalently) and tag as a release.

**Comment by AarynnCarter** [comment]
Okay sounds good, I will make a `develop` branch now. In that case I think it is okay to merge this branch into develop as is, then we can make a new branch to add documentation for more advanced aspects like contrast calibration and companion fitting once the actual contrast calibration code has been merged into `develop` also.

**Comment by mperrin** [comment]
>  I will make a develop branch now. In that case I think it is okay to merge this branch into develop as is.

Copy that. Doing so now.

**Pull request merged**
