### PR TITLE
Code adjustments to fix the API for readthedocs

### PR DESCRIPTION
**Pull request by AarynnCarter**
Readthedocs currently isn't compiling our API correctly, these changes resolve the issues for my local html compiling. 

The only caveat is that I can't get the make_psfmasks.py file to be documented correctly. When running the Makefile it struggles to get through the file due to the following lines:

```
pxsc = nircam._pixelscale_long  # arcsec
xoff, yoff = crpix1 - xcen - offset_lwb[filt] / pxsc, crpix2 - ycen
```

It's unable to recognize the pxsc as a float, so can't step through the calculation. If I run the file on its own everything is fine, so must be some issue with the Makefile behaviour.

### CODE REVIEW

**Comment by mperrin** [comment]
Is the addition of the 3 binary mask files in this PR intentional? That doesn't seem like it has much to do with docs building, or does it? 

e.g. spaceKLIP/resources/transmissions/JWST_MIRI_F1065C_transmission_webbpsf-ext_v2.fits

**Comment by AarynnCarter** [comment]
@mperrin It doesn't, let me undo that.

**Comment by AarynnCarter** [comment]
@mperrin Okay added some more tweaks to get the API sharpened up / connected to the source code. I won't make any changes on top of this.

**Review by mperrin — APPROVED** [review]
Look good to me

**Pull request merged**
